# @package _global_
name: daps
sampler:
  _target_: genmol.DAPS_sampler.DAPSSampler
  num_steps: ${daps.num_steps}
  alpha: ${daps.alpha}
  mh_steps: ${daps.mh_steps}
  max_mutations: ${daps.max_mutations}
  remask_max: ${daps.remask_max}
  remask_min: ${daps.remask_min}
  remask_schedule: ${daps.remask_schedule}
  ode_steps: ${daps.ode_steps}
  seed: ${seed}

daps:
  num_steps: 50 #consider making this bigger
  alpha: 100. #forward operator weight
  mh_steps: 2 #consider making this smaller
  max_mutations: 1
  remask_max: 0.6
  remask_min: 0.05
  remask_schedule: linear
  ode_steps: 100 #20 produces very poor quality generations #number of ODE steps for reverse diffusion
