"""
Train an affinity surrogate for GenMol from pre-generated data.

Uses the same 1D UNet architecture as the QED surrogate, but trained on
(token_ids, affinity_score) pairs generated by FlashAffinity.

Unlike the QED surrogate (online generation), data is loaded from disk
because FlashAffinity inference is expensive (FABind+ docking + model).

Usage:
    python scripts/train_affinity_surrogate.py \
        --dataset_path outputs/affinity_data/affinity_dataset.pt \
        --num_epochs 100 \
        --batch_size 128 \
        --lr 1e-4
"""

import argparse
import json
import os
import time

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset, random_split

import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from genmol.qed_surrogate import QEDSurrogate, save_surrogate


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------

def train(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # --- Load dataset ---
    print(f"Loading dataset from {args.dataset_path}...")
    data = torch.load(args.dataset_path, weights_only=False)
    token_ids = data["token_ids"]
    affinity_scores = data["affinity_scores"]
    prot_id = data.get("prot_id", "unknown")
    print(f"  {len(token_ids)} samples, protein: {prot_id}")
    print(f"  Affinity range: [{affinity_scores.min():.3f}, "
          f"{affinity_scores.max():.3f}]")
    print(f"  Affinity mean:  {affinity_scores.mean():.3f}")

    # --- Normalize affinity scores (optional, for better training) ---
    if args.normalize:
        aff_mean = affinity_scores.mean()
        aff_std = affinity_scores.std()
        affinity_scores = (affinity_scores - aff_mean) / aff_std.clamp(min=1e-6)
        print(f"  Normalized: mean={aff_mean:.3f}, std={aff_std:.3f}")
    else:
        aff_mean = None
        aff_std = None

    # --- Train/val split ---
    dataset = TensorDataset(token_ids, affinity_scores)
    n_val = max(int(len(dataset) * args.val_frac), 1)
    n_train = len(dataset) - n_val
    train_set, val_set = random_split(
        dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(42))
    print(f"  Train: {n_train}, Val: {n_val}")

    train_loader = DataLoader(
        train_set, batch_size=args.batch_size, shuffle=True,
        num_workers=0, pin_memory=True)
    val_loader = DataLoader(
        val_set, batch_size=args.batch_size, shuffle=False,
        num_workers=0, pin_memory=True)

    # --- Build surrogate ---
    surrogate = QEDSurrogate(
        vocab_size=args.vocab_size,
        max_seq_len=args.max_seq_len,
        embed_dim=args.embed_dim,
        base_channels=args.base_channels,
        channel_mult=tuple(args.channel_mult),
        num_res_blocks=args.num_res_blocks,
        dropout=args.dropout,
        pad_token_id=args.pad_token_id,
    ).to(device)

    n_params = sum(p.numel() for p in surrogate.parameters())
    print(f"AffinitySurrogate: {n_params:,} parameters")

    # --- Optimizer ---
    optimizer = torch.optim.AdamW(
        surrogate.parameters(), lr=args.lr, weight_decay=args.weight_decay)

    # --- Output ---
    os.makedirs(args.output_dir, exist_ok=True)

    # --- Training loop ---
    train_losses = []
    val_losses = []
    best_val_loss = float("inf")
    t_start = time.time()

    print(f"\nTraining for {args.num_epochs} epochs...")
    for epoch in range(1, args.num_epochs + 1):
        surrogate.train()
        epoch_loss = 0.0
        n_batches = 0

        for batch_ids, batch_aff in train_loader:
            batch_ids = batch_ids.to(device)
            batch_aff = batch_aff.to(device)

            pred = surrogate(batch_ids)
            loss = F.mse_loss(pred, batch_aff)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(
                surrogate.parameters(), args.grad_clip)
            optimizer.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()
            n_batches += 1

        avg_train = epoch_loss / max(n_batches, 1)
        train_losses.append(avg_train)

        # --- Validation ---
        surrogate.eval()
        val_loss = 0.0
        n_val_batches = 0
        with torch.no_grad():
            for batch_ids, batch_aff in val_loader:
                batch_ids = batch_ids.to(device)
                batch_aff = batch_aff.to(device)
                pred = surrogate(batch_ids)
                val_loss += F.mse_loss(pred, batch_aff).item()
                n_val_batches += 1

        avg_val = val_loss / max(n_val_batches, 1)
        val_losses.append(avg_val)

        if epoch % args.log_every == 0:
            elapsed = time.time() - t_start
            print(f"  epoch {epoch}/{args.num_epochs}  "
                  f"train={avg_train:.6f}  val={avg_val:.6f}  "
                  f"[{elapsed:.0f}s]")

        if avg_val < best_val_loss:
            best_val_loss = avg_val
            save_surrogate(
                surrogate,
                os.path.join(args.output_dir, "affinity_surrogate_best.pt"),
                step=epoch, val_loss=best_val_loss,
                prot_id=prot_id,
                normalize_mean=float(aff_mean) if aff_mean is not None else None,
                normalize_std=float(aff_std) if aff_std is not None else None,
            )

    # --- Save final ---
    save_surrogate(
        surrogate,
        os.path.join(args.output_dir, "affinity_surrogate_final.pt"),
        step=args.num_epochs,
        val_loss=val_losses[-1] if val_losses else None,
        prot_id=prot_id,
        normalize_mean=float(aff_mean) if aff_mean is not None else None,
        normalize_std=float(aff_std) if aff_std is not None else None,
    )

    # --- Loss curves ---
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(train_losses, linewidth=1.5, label="train")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("MSE Loss")
    ax1.set_title("Training loss")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    ax2.plot(val_losses, "o-", markersize=2, linewidth=1, label="val")
    ax2.set_xlabel("Epoch")
    ax2.set_ylabel("MSE Loss")
    ax2.set_title("Validation loss")
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(os.path.join(args.output_dir, "affinity_loss_curve.png"),
                dpi=150)
    plt.close()

    # --- Metrics ---
    with open(os.path.join(args.output_dir, "affinity_metrics.json"), "w") as f:
        json.dump({
            "n_params": n_params,
            "n_train": n_train,
            "n_val": n_val,
            "num_epochs": args.num_epochs,
            "best_val_loss": best_val_loss,
            "final_train_loss": train_losses[-1] if train_losses else None,
            "prot_id": prot_id,
            "normalized": args.normalize,
            "elapsed_sec": time.time() - t_start,
        }, f, indent=2)

    print(f"\nDone. Best val loss: {best_val_loss:.6f}")
    print(f"Saved to {args.output_dir}/")
    print(f"Total time: {time.time() - t_start:.0f}s")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Train affinity surrogate from pre-generated data")

    # Data
    parser.add_argument("--dataset_path", type=str, required=True,
                        help="Path to affinity_dataset.pt")
    parser.add_argument("--val_frac", type=float, default=0.1)
    parser.add_argument("--normalize", action="store_true",
                        help="Normalize affinity scores (zero mean, unit var)")

    # Architecture (same defaults as QED surrogate)
    parser.add_argument("--vocab_size", type=int, default=1882)
    parser.add_argument("--max_seq_len", type=int, default=256)
    parser.add_argument("--embed_dim", type=int, default=128)
    parser.add_argument("--base_channels", type=int, default=64)
    parser.add_argument("--channel_mult", type=int, nargs="+",
                        default=[1, 2, 4, 4])
    parser.add_argument("--num_res_blocks", type=int, default=1)
    parser.add_argument("--dropout", type=float, default=0.1)
    parser.add_argument("--pad_token_id", type=int, default=3)

    # Training
    parser.add_argument("--num_epochs", type=int, default=100)
    parser.add_argument("--batch_size", type=int, default=128)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--grad_clip", type=float, default=10.0)
    parser.add_argument("--log_every", type=int, default=5)

    # Output
    parser.add_argument("--output_dir", type=str,
                        default="outputs/affinity_surrogate")

    args = parser.parse_args()
    train(args)


if __name__ == "__main__":
    main()
